version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
#     command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - staticfiles:/usr/local/lib/python3.12/site-packages/django/contrib/admin/static/admin
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/www/static/app
      - staticfiles:/www/static/app/admin
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles:
